import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { QueryProvider } from "@/components/QueryProvider";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();

	return (
		<SessionProvider session={session}>
			<html lang="en">
				<body
					className={cn(
						"relative h-full font-sans antialiased",
						geistSans.variable,
						geistMono.variable
					)}
				>
					<QueryProvider>
						<main className="relative flex flex-col min-screen">
							<div className="flex-grow flex-1">{children}</div>
						</main>
					</QueryProvider>
				</body>
			</html>
		</SessionProvider>
	);
}
